name: Pylint Changed Files and Cache Dependencies

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        name: List the state of the pip cache
        continue-on-error: true
        run: |
          ls -l ~/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed_files.outputs.all_changed_files }}" | xargs -n 1 pylint
